# Generated by Django 3.2.8 on 2023-02-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlists',
            name='uid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playlists',
            name='is_shuffle',
            field=models.BooleanField(default=True),
        ),
    ]
