# Generated by Django 3.2.8 on 2023-02-21 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playlists', '0002_auto_20230205_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('cover', models.CharField(max_length=200)),
                ('biography', models.TextField()),
                ('sort_biography', models.TextField()),
                ('national', models.CharField(max_length=200)),
                ('birthday', models.CharField(max_length=100)),
                ('real_name', models.CharField(max_length=200)),
                ('total_follow', models.IntegerField()),
                ('follow', models.IntegerField()),
                ('artist_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlists.artists')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
