# Generated by Django 3.2.8 on 2023-02-08 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playlists', '0002_auto_20230205_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('thumbnail', models.CharField(max_length=300)),
                ('is_offical', models.BooleanField(default=True)),
                ('release_date', models.CharField(max_length=100)),
                ('sort_description', models.TextField(default='null')),
                ('released_at', models.IntegerField()),
                ('pr', models.BooleanField(default=False)),
                ('artist_names', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('alias', models.CharField(max_length=200)),
                ('is_offical', models.BooleanField(default=True)),
                ('user_name', models.CharField(default='null', max_length=100)),
                ('artist_names', models.CharField(max_length=100)),
                ('is_world_wide', models.BooleanField(default=True)),
                ('thumbnail_m', models.CharField(max_length=400)),
                ('thumbnail', models.CharField(max_length=400)),
                ('duration', models.IntegerField()),
                ('zing_choice', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('pre_release', models.BooleanField(default=False)),
                ('release_date', models.IntegerField()),
                ('is_indie', models.BooleanField(default=False)),
                ('streaming_status', models.IntegerField(default=1)),
                ('allow_audio_ads', models.BooleanField(default=True)),
                ('has_lyric', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SongOfPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlists.playlists')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist_detail.songs')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtistOfSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlists.artists')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist_detail.songs')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtistOfAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist_detail.albums')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlists.artists')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlbumOfSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist_detail.albums')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist_detail.songs')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
